In [1]:
import pandas as pd

In [9]:
data = pd.read_csv('../data/sp500_all.csv')

In [11]:
data['Date'] = pd.to_datetime(data['Date'])
data = data.sort_values(by='Date')

In [12]:
data.head(1000)

,Date,Open,High,Low,Close,Adj Close,Volume,ticker
0,2020-01-02,177.679993,180.009995,177.139999,180.000000,152.158829,3601700,MMM
10872,2020-01-02,50.189999,50.340000,49.049999,49.250000,36.356846,8717200,MO
134039,2020-01-02,64.910797,65.023476,63.267605,63.511738,54.496117,2874968,K
133534,2020-01-02,24.809999,24.900000,24.540001,24.709999,21.893494,2876000,JNPR
133029,2020-01-02,139.789993,141.100006,139.259995,141.089996,125.020401,10803700,JPM
...,...,...,...,...,...,...,...,...
70411,2020-01-06,56.990002,57.759998,56.660000,57.660000,56.984768,5504300,DAL
86571,2020-01-06,142.110001,143.529999,141.710007,143.479996,138.978271,729200,EFX
94146,2020-01-06,266.859985,267.299988,263.750000,267.160004,257.681122,349900,FDS
87581,2020-01-06,80.639999,81.449997,80.169998,81.029999,70.380264,1764300,EQR
249128,2020-01-06,144.242722,144.495148,142.941742,143.640778,139.612045,972423,ZBH